apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistentvolume-pod
  labels:
    name: pv-pod 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pv-pod
  template:
    metadata:
      labels:
        name: pv-pod
    spec:
      volumes:
      - name: persistentvolume-storage
        persistentVolumeClaim:
          claimName: persistentvolume-claim
      containers:
      - name: frontend
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistentvolume-storage
        ports:
        - containerPort:80
      - name: backend
        image: debian
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistentvolume-storage
        command: ["/bin/sh", "-c"]
        args: 
        - while true; do
            "echo Hello from the backend \r\n > /usr/share/nginx/html/index.html";
            sleep 50;
          done
