apiVersion: v1
kind: Pod
metadata:
  name: persistentvolume-pod
spec:
  volumes:
    - name: persistentvolume-storage
      persistentVolumeClaim:
        claimName: persistentvolume-claim
  containers:
  - name: container1
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: persistentvolume-storage
  
  - name: container2
    image: nginx
    volumeMounts:
      - mountPath: /work/data
        name: persistentvolume-storage
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the container > /work/data/index.html"]
