apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistentvolume-pod
  labels:
    app: pv-pod 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-pod
  template:
    metadata:
      labels:
        app: pv-pod
    spec:
      volumes:
      - name: persistentvolume-storage
        persistentVolumeClaim:
          claimName: persistentvolume-claim
      containers:
      - name: frontend
        image: nginx:1.8
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistentvolume-storage
        ports:
        - containerPort:80
          name: "http-server"
      - name: backend
        image: debian
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistentvolume-storage
        command: ["/bin/sh", "-c"]
        args: 
        - while true; do
            echo "Hello from the backend! \r\n" >> "/usr/share/nginx/html/index.html";
            sleep 100;
          done
