apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/szf3"
