apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-pod
  labels:
    name: q-pod 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: q-pod
  template:
    metadata:
      labels:
        name: q-pod
    spec:
      containers:
      - name: query
        image: byrnedo/alpine-curl
        command: ["ash", "-c"]
        args:
        - while true; do
            curl master-26:31414;
            sleep 50;
          done
